[campaign]
id = 468510

[creators]
# TODO: FIXME: User IDs?
twitch = [
    "gathe_",
    # "inkierain",
    "kkywi",
    "megapigstep",
    "tridegd",

    # Test accounts
    # "linustech",
    # "xqc",
    # "loltyler1",
    # "summit1g",
    # "amouranth",
    # "rainbow6",
    # "bobross",
    # "dusterthefirst",
]

youtube = [
    "@ReapeeRon",
    "@Santaa.",

    # Test accountts
    # "@LofiGirl",
    # "@dusterthefirst",
    # "@therealgathe",
    # "@ludwig",
    # "@jaidenanimations"
]
