{
 "title": "Creators for a Cause",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Live Stream Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Creator Live History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum(live_creators{service=\"Twitch\"}) by (id, username)",
     "legendFormat": "{{username}}"
    },
    {
     "expr": "sum(live_creators{service=\"Youtube\"}) by (id, username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Live Creators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (live_creators)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  { "title": "API Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Youtube Qouta Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "targets": [
    { "expr": "youtube_quota_usage_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Youtube Qouta Usage Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "per hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (increase(youtube_quota_usage_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Youtube Qouta Usage Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "per day" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (increase(youtube_quota_usage_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Youtube Qouta Usage Per Day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (increase(youtube_quota_usage_total[24h])) / 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Currently Deployed Git Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_info{app=\"creatorsforacause\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Deployed Versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_info{app=\"creatorsforacause\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments Per Week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (hash) (count_over_time(build_info{app=\"creatorsforacause\"}[7d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "build_info{app=\"creatorsforacause\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Deployments",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "build_info{app=\"creatorsforacause\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}